# Generated by Django 5.2.6 on 2025-10-04 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_useranswer'),
    ]

    operations = [
    ]
