# Generated by Django 5.2.6 on 2025-10-05 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20251005_0042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstatistics',
            name='quizzes_by_difficulty',
        ),
    ]
