# Generated by Django 5.2.6 on 2026-09-29 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_remove_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquiz',
            name='current_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userquiz',
            name='question_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='userquiz',
            name='question_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
