# Generated by Django 5.2.6 on 2026-09-30 06:52

import django.db.models.deletion
import quiz.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_teachers_group'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_bank', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('mode', models.CharField(choices=[('scheduled', 'Scheduled (teacher starts it, fixed time)'), ('open', 'Open (anytime, no timer)')], default='scheduled', max_length=10)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('seat_limit', models.PositiveIntegerField()),
                ('token', models.CharField(default=quiz.models.new_exam_token, editable=False, max_length=32, unique=True)),
                ('status', models.CharField(default='draft', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to=settings.AUTH_USER_MODEL)),
                ('questions', models.ManyToManyField(related_name='exams', to='quiz.question')),
            ],
        ),
        migrations.CreateModel(
            name='ExamAllowed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=254)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowed', to='quiz.exam')),
            ],
            options={
                'unique_together': {('exam', 'email')},
            },
        ),
    ]
