# Generated by Django 5.2.6 on 2026-09-30 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_exam_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='examattempt',
            name='last_rejoin_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='rejoins',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
