# Generated by Django 5.2.6 on 2026-10-01 22:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_exam_taking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='examattempt',
            name='blocked_devices',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='challenger_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='challenger_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='challenger_label',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='device_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='device_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='device_label',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='extra_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='freezes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='frozen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ExamEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=20)),
                ('detail', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='quiz.examattempt')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='quiz.exam')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
