# Generated by Django 5.2.6 on 2026-10-02 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_device_lock'),
    ]

    operations = [
        migrations.AddField(
            model_name='examattempt',
            name='device_seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='intrusions',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='last_intruder_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='last_intruder_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='last_intruder_label',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='last_intrusion_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
