"""
Django settings for quiz_project project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import sys
from pathlib import Path
import dj_database_url
from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env if present
load_dotenv(BASE_DIR / '.env')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# Debug mode is OFF unless it is asked for, so a server that was set up in a hurry fails closed, not open.
# It is ON by default only for local commands (python manage.py runserver / test / migrate ...), which is how
# you work on your own computer. A production server runs through gunicorn, not manage.py, so it gets the safe
# default and must be configured with the environment variables below. DJANGO_DEBUG=True/False overrides both.
_debug_setting = os.environ.get('DJANGO_DEBUG')
if _debug_setting is not None:
    DEBUG = _debug_setting.strip().lower() in ('true', '1', 't')
else:
    DEBUG = os.path.basename(sys.argv[0]) == 'manage.py'

SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY')
if not SECRET_KEY:
    if not DEBUG:
        raise ImproperlyConfigured('DJANGO_SECRET_KEY must be set (see .env.example) when debug is off')
    SECRET_KEY = 'django-insecure-dev-only-key'

# Only these Host names are served. This also stops a forged Host header from poisoning the links in emails.
_hosts = [h.strip() for h in os.environ.get('DJANGO_ALLOWED_HOSTS', '').split(',') if h.strip()]
if os.environ.get('RENDER_EXTERNAL_HOSTNAME'):  # Render tells the site its own address (only while it runs, not during the build)
    _hosts.append(os.environ['RENDER_EXTERNAL_HOSTNAME'])  # a platform variable: a visitor cannot send an environment variable
if _hosts:
    ALLOWED_HOSTS = _hosts
elif DEBUG:
    ALLOWED_HOSTS = ['localhost', '127.0.0.1', '[::1]']
else:
    raise ImproperlyConfigured('DJANGO_ALLOWED_HOSTS must be set (for example "quiz.example.edu") when debug is off')

# Security Headers
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'
CSRF_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_SECURE = not DEBUG
SECURE_REFERRER_POLICY = 'same-origin'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_otp',                       # two-factor sign-in: codes from an authenticator app...
    'django_otp.plugins.otp_totp',
    'django_otp.plugins.otp_static',    # ...and recovery codes
    'quiz',
]

MIDDLEWARE = [
    'quiz.middleware.AssumeHttpsMiddleware',  # FIRST: on a host that ends HTTPS itself, tell Django the page is https (ASSUME_HTTPS)
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # serves the static files (CSS, fonts) from the app itself on a real server
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django_otp.middleware.OTPMiddleware',  # request.user.is_verified(): has this session passed the second step?
    'quiz.middleware.RequestCapMiddleware',  # catch-all cap per address and per signed-in user (REQUEST_CAPS)
    'quiz.middleware.TwoFactorGateMiddleware',  # a signed-in but unverified user can only reach the 2FA pages
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'quiz.middleware.AdminAccessMiddleware',  # Custom middleware to protect admin interface
    'quiz.middleware.DeviceCookieMiddleware',  # marks each browser on exam pages (device lock)
]

ROOT_URLCONF = 'quiz_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [ BASE_DIR / 'templates' ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'quiz.context.role',
            ],
        },
    },
]

WSGI_APPLICATION = 'quiz_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# PostgreSQL only. DATABASE_URL (postgres://user:password@host:5432/name) names the database. There is no fallback: a
# server that forgot to set it stops with a plain message instead of quietly starting on an empty throwaway database.
# "manage.py test" reads TEST_DATABASE_URL instead and ignores DATABASE_URL, so running the tests can never reach the live
# database (on your own computer both can hold the same address: Django makes and removes its own test_ database).
_database_setting = 'TEST_DATABASE_URL' if 'test' in sys.argv else 'DATABASE_URL'
_database_url = os.environ.get(_database_setting)
if not _database_url:
    raise ImproperlyConfigured(f'{_database_setting} must be set to a PostgreSQL address (see .env.example)')
# conn_max_age: keep a connection for a minute instead of reconnecting on every request. conn_health_checks: test it
# before reuse, because a database that sleeps when idle (Neon) closes its connections.
DATABASES = {'default': dj_database_url.parse(_database_url, conn_max_age=60, conn_health_checks=True)}
# A time limit on each connection attempt (per address, in seconds). Without one a database that is down, waking up (Neon) or
# unreachable (a blocked port) holds every request that needs it for minutes, until the operating system gives up (260 seconds
# measured here), and a few stuck requests use up all the server's threads. The address can choose its own: ...?connect_timeout=5
DATABASES['default'].setdefault('OPTIONS', {}).setdefault('connect_timeout', 10)

# Behind a host's proxy the visitor's address and the page's scheme come from the proxy (quiz/util.client_ip and
# quiz.middleware.AssumeHttpsMiddleware). Both are off here, so a direct connection is never believed about who it is.
# TRUSTED_PROXY_COUNT = how many proxies of the HOST are in front of the app (Zoho Catalyst: 1; Render: measure it). Set it only when
# ALL traffic really comes through them, and only to the number the superadmin's "how the site sees your address" panel (Locked
# logins page) confirms. ASSUME_HTTPS = the host ends HTTPS itself and passes plain requests on (Zoho and Render: True).
TRUSTED_PROXY_COUNT = int(os.environ.get('DJANGO_TRUSTED_PROXY_COUNT') or 0)
ASSUME_HTTPS = os.environ.get('DJANGO_ASSUME_HTTPS', '').strip().lower() in ('true', '1', 't')
if ASSUME_HTTPS:  # that host ends HTTPS and sends HSTS itself (Zoho does), so Django's own redirect and HSTS would only repeat it
    SILENCED_SYSTEM_CHECKS = ['security.W004', 'security.W008']  # `check --deploy` warnings about exactly those two

# Login locks and rate-limit counters live in this cache. Django's default keeps only 300 entries and silently
# drops the oldest when full, which would drop a lock; this keeps plenty. ponytail: per process, so with several
# workers (gunicorn) or a restart the counters are not shared: use a database or Redis cache then.
CACHES = {'default': {'BACKEND': 'django.core.cache.backends.locmem.LocMemCache', 'OPTIONS': {'MAX_ENTRIES': 50_000}}}

# With DEBUG off, Django's own logging drops every error (its console handler only works in debug mode), so a crash on a
# real server would leave no trace. This sends warnings and errors, with their traceback, to the console, which is where a
# host collects logs. It adds no request data: never log request headers (a host's gateway puts credentials in some).
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {'plain': {'format': '%(asctime)s %(levelname)s %(name)s: %(message)s'}},
    'handlers': {'console': {'class': 'logging.StreamHandler', 'formatter': 'plain'}},
    'loggers': {'django': {'handlers': ['console'], 'level': 'INFO'}},
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 8,  # Require at least 8 characters
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Admin security settings
ADMIN_URL = 'admin/'  # You can change this to something more unique for extra security
ADMIN_ENABLED = True

# Session security settings
SESSION_COOKIE_HTTPONLY = True  # Prevents JavaScript from accessing cookies
SESSION_EXPIRE_AT_BROWSER_CLOSE = True  # Session expires when browser closes


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'  # USE_TZ stays on: DB keeps UTC, pages show IST

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [ BASE_DIR / "static" ]
STATIC_ROOT = BASE_DIR / "staticfiles"
if DEBUG:  # your own computer and the tests: serve straight from the app folders, no collectstatic needed
    WHITENOISE_USE_FINDERS = True
    WHITENOISE_AUTOREFRESH = True
else:
    # A real server: `manage.py collectstatic` (run with DJANGO_DEBUG=False too, or it makes plain names) copies every static
    # file to STATIC_ROOT with a fingerprint in its name (style.css -> style.5f3a1c.css) and a compressed twin, so browsers keep
    # a file for a year and a new deploy is picked up at once. A page that names a file that was not collected is an error.
    STORAGES = {'default': {'BACKEND': 'django.core.files.storage.FileSystemStorage'},
                'staticfiles': {'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage'}}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Verification and password-reset links expire after 24 hours (the emails say so)
PASSWORD_RESET_TIMEOUT = 24 * 60 * 60

# Login redirects
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/accounts/login/'

# Email Settings
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', 'srmverify@gmail.com')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')

if EMAIL_HOST_PASSWORD:
    EMAIL_BACKEND = os.environ.get('EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')
else:
    # Use console backend if no password provided (avoids crash during dev/tests)
    EMAIL_BACKEND = os.environ.get('EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend')

EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True').lower() in ('true', '1', 't')
# Give up on the mail server after this many seconds. Without it a blocked mail port (campus Wi-Fi, a host that blocks
# SMTP) leaves every register / reset request hanging until the operating system gives up, and a few of them freeze the site.
EMAIL_TIMEOUT = int(os.environ.get('EMAIL_TIMEOUT', 10))

DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', f'SRM Quiz Platform <{EMAIL_HOST_USER}>')
# Tests create many users; a fast hasher makes the suite several times quicker. Only active under "manage.py test".
if "test" in __import__("sys").argv:
    PASSWORD_HASHERS = ["django.contrib.auth.hashers.MD5PasswordHasher"]

# Requests per minute: one network address and one signed-in user (a student in an exam makes about 10 a minute).
# The address cap is high because a whole campus shares ONE public address: two classes of 50 measured about 950 a minute,
# so the old 1200 would have cut off everyone behind the campus address from the third class on. Switched off under
# "manage.py test": the whole suite comes from one address in about a minute. The tests that need it turn it on with small numbers.
REQUEST_CAPS = {'address': 6000, 'user': 300}
# The "someone is guessing your password" email is sent from a background thread (so the login page is not slowed down).
LOCK_ALERT_BACKGROUND = True
# Two-factor sign-in (see quiz/two_factor.py). These roles cannot use the site without it; anyone else may turn it on.
TWO_FACTOR_REQUIRED_ROLES = {'admin', 'teacher'}
TRUSTED_BROWSER_DAYS = 30        # "remember this browser" skips the code for this long (password still needed)
OTP_TOTP_ISSUER = 'SRMIST Quiz'  # the name the authenticator app shows
OTP_TOTP_THROTTLE_FACTOR = 2     # after a wrong code: wait 2, 4, 8, 16 ... seconds before the next try
OTP_STATIC_THROTTLE_FACTOR = 2
OTP_ADMIN_HIDE_SENSITIVE_DATA = True  # the admin site must not show anyone's secret key or recovery codes
# A browser an account has not used before gets one email ("new sign-in from Firefox on Windows").
NEW_BROWSER_ALERTS = True
if "test" in __import__("sys").argv:
    REQUEST_CAPS = {}
    LOCK_ALERT_BACKGROUND = False  # a thread would put the mail in a later test's outbox
    TWO_FACTOR_REQUIRED_ROLES = set()  # the older tests sign teachers in without a code; the 2FA tests turn this on
    NEW_BROWSER_ALERTS = False
    LOGGING['handlers']['console']['level'] = 'CRITICAL'  # the tests make plenty of 404s and 403s on purpose: keep the output readable
